import { type NextPage } from "next";
import Head from "next/head";
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { User } from "@clerk/nextjs/dist/api";
import { Background } from "~/background/Background";
import { Section } from "~/layout/Section";
import { NavbarTwoColumns } from "~/navigation/NavbarTwoColumns";



const Hero = () => {
  const { isSignedIn } = useUser();
  
  return (
    <Background color='' >
      <Section yPadding="py-6">
        <NavbarTwoColumns logo={undefined} >
          <li className='text-blue-900'>
            {!isSignedIn &&  <SignInButton mode='modal' />}
            {isSignedIn &&  <SignOutButton />}
          </li>
        </NavbarTwoColumns>
      </Section>

      <Section yPadding="pt-20 pb-32">

      </Section>
    </Background>
  )
};

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
    </>
  );
};

export default Home;
